name: duet_example
description: Demonstrates how to use the duet plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  duet:
    path: ../
  cupertino_icons: ^1.0.2
  dio:
  path_provider:
  get:
  json_annotation: 4.6.0
  file_picker:
  retrofit: 3.0.1
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: 6.3.1
  retrofit_generator: '>=3.0.0 <4.0.0'

  video_player: ^2.3.0
flutter:
  uses-material-design: true
  assets:
    - assets/